###Create new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "We",
  "address": "Address",
  "email": "we@gmail.com",
  "dateOfBirth": "1996-09-09",
  "registeredDate": "2025-11-28"
}

###