spring:
#  application:
#   name: patient-service
#   # WE user docker and edit configuration
#  datasource:
#    url: jdbc:postgresql://localhost:5432/db
#    driver-class-name: org.postgresql.Driver
#    password: password
#    username: admin_user
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  sql:
#    init:
#      mode: always
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    bootstrap-servers: kafka:9092

server:
  port: 4000

logging:
  level:
    root: info


# for grpc dati che si potrebbe ceare un config server
billing:
  service:
    address: billing-service
    grpc:
      port: 9001