spring:
  application:
   name: patient-service
   # WE user docker and edit configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    driver-class-name: org.postgresql.Driver
    password: password
    username: admin_user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

server:
  port: 4000

logging:
  level:
    root: info


# for grpc dati
billing:
  service:
    address: billing-service
    grpc:
      port: 9001